distribution_params_modifier_ui <- function(id) {
  ns <- shiny::NS(id)

  shiny::uiOutput(
    outputId = ns("params")
  )
}

distribution_params_modifier_server <- function(id, .values, distribution_id_r) {
  shiny::moduleServer(
    id,
    function(input, output, session) {

      ns <- session$ns

      max_index_rv <- shiny::reactiveVal(0)

      param_names_r <- shiny::reactive({
        distribution_helper$get_param_names(distribution_id_r())
      })

      param_ids_r <- shiny::reactive({
        distribution_helper$get_param_ids(distribution_id_r())
      })

      output$params <- shiny::renderUI({
        purrr::pmap(
          list(
            param_ids_r(),
            param_names_r(),
            seq_along(param_names_r())
          ),
          function(id, name, index) {
            if (index > max_index_rv()) {
              # Increment max index
              max_index_rv(index)

              output[["param_error" %_% index]] <- shiny::renderUI({
                # Visible output is only generated by validate, therefore return
                # NULL
                distribution_helper$validate_param_value(
                  value = input[["param" %_% index]],
                  param_id = param_ids_r()[index],
                  distribution_id = distribution_id_r()
                )
                NULL
              })
            }

            htmltools::tagList(
              shiny::numericInput(
                inputId = ns("param" %_% index),
                label = htmltools::HTML(name),
                value = 1
              ),
              shiny::uiOutput(
                outputId = ns("param_error" %_% index)
              )
            )
          }
        )
      })

      params_r <- shiny::reactive({
        x <- purrr::map2(
          param_names_r(), seq_along(param_names_r()),
          function(name, index) {
            input[["param" %_% index]]
        })

        names(x) <- param_ids_r()
        x
      })

      error_r <- shiny::reactive({
        purrr::map2_lgl(
          param_ids_r(), seq_along(param_ids_r()),
          function(id, index) {
            !distribution_helper$is_valid_param_value(
              value = shiny::req(input[["param" %_% index]]),
              param_id = id
            )
          }
        ) %>% any()
      })

      return_list <- list(
        error_r = error_r,
        params_r = params_r
      )

      return(return_list)
    }
  )
}
